%Version 2.1 April 2023
% See section 11 of the User Manual for version history
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                 %%
%% Please do not use \input{...} to include other tex files.       %%
%% Submit your LaTeX manuscript as one .tex document.              %%
%%                                                                 %%
%% All additional figures and files should be attached             %%
%% separately and not embedded in the \TeX\ document itself.       %%
%%                                                                 %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[sn-nature,pdflatex]{sn-jnl}

%%%% Standard Packages
%%<additional latex packages if required can be included here>

\usepackage{graphicx}%
\usepackage{multirow}%
\usepackage{amsmath,amssymb,amsfonts}%
\usepackage{amsthm}%
\usepackage{mathrsfs}%
\usepackage[title]{appendix}%
\usepackage{xcolor}%
\usepackage{textcomp}%
\usepackage{manyfoot}%
\usepackage{booktabs}%
\usepackage{algorithm}%
\usepackage{algorithmicx}%
\usepackage{algpseudocode}%
\usepackage{listings}%
%%%%

%%%%%=============================================================================%%%%
%%%%  Remarks: This template is provided to aid authors with the preparation
%%%%  of original research articles intended for submission to journals published
%%%%  by Springer Nature. The guidance has been prepared in partnership with
%%%%  production teams to conform to Springer Nature technical requirements.
%%%%  Editorial and presentation requirements differ among journal portfolios and
%%%%  research disciplines. You may find sections in this template are irrelevant
%%%%  to your work and are empowered to omit any such section if allowed by the
%%%%  journal you intend to submit to. The submission guidelines and policies
%%%%  of the journal take precedence. A detailed User Manual is available in the
%%%%  template package for technical guidance.
%%%%%=============================================================================%%%%

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}


\raggedbottom




% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}





\begin{document}


\title[MAP-reduction-meta]{Durably reducing consumption of meat and
animal products is an unsolved problem: results from a meta-analysis}

%%=============================================================%%
%% Prefix	-> \pfx{Dr}
%% GivenName	-> \fnm{Joergen W.}
%% Particle	-> \spfx{van der} -> surname prefix
%% FamilyName	-> \sur{Ploeg}
%% Suffix	-> \sfx{IV}
%% NatureName	-> \tanm{Poet Laureate} -> Title after name
%% Degrees	-> \dgr{MSc, PhD}
%% \author*[1,2]{\pfx{Dr} \fnm{Joergen W.} \spfx{van der} \sur{Ploeg} \sfx{IV} \tanm{Poet Laureate}
%%                 \dgr{MSc, PhD}}\email{iauthor@gmail.com}
%%=============================================================%%

\author*[1]{\fnm{Seth
Ariel} \sur{Green} }\email{\href{mailto:setgree@stanford.edu}{\nolinkurl{setgree@stanford.edu}}}

\author[1]{\fnm{Maya} \sur{Mathur} }

\author[2]{\fnm{Benny} \sur{Smith} }



  \affil[1]{\orgdiv{Humane and Sustainable Food Lab}, \orgname{Stanford
University}}
  \affil[2]{\orgname{Allied Scholars for Animal Protection}}

\abstract{\textbf{Purpose}: \textbf{Methods:} \textbf{Results:}
\textbf{Conclusion:}}

\keywords{key, dictionary, word}



\maketitle

\section{Introduction}\label{sec1}

Consumption of meat and animal products (MAP) is increasingly recognized
as a major contributor to premature deaths
\citep{willett2019, landry2023}, public health risks
\citep{slingenbergh2004, graham2008}, ecological harms
\citep{greger2010} and climate change
\citep{scarborough2023, koneswaran2008} as well as an ethical crisis in
its own right \citep{kuruc2023, singer2023}.

Supply-side interventions, such as banning or taxing certain practices
or products, risk political backlash if they do not have broad public
support. It is of vital importance, therefore, to assess which
strategies and theoretical perspectives lead to the largest and most
durable reductions in demand for MAP products, under which conditions,
and for which populations. We address these questions with a
meta-analysis of the most rigorous studies aimed at reducing MAP
consumption.

The research on diet and its personal, cultural, and practical
antecedents on the one hand and its consequences for health, the
environment, and animal welfare on the other is vast. By our count,
there have been at least 118 previous reviews on these questions in the
past two decades, with at least thirty-seven focused specifically on MAP
reduction. However, comparatively few of these are quantitative, and
most prior reviews investigated particular approaches, for example
choice architecture \citep{bianchi2018restructuring}, appeals to animal
welfare \citep{mathur2021effectiveness}, or literacy interventions
\citep{DiGennaro2024}, rather than comparing approaches to one another.
Moreover, two prior investigations revealed three common gaps in the MAP
literature: a dearth of long-term follow-ups, consumption outcomes, and
inattention to the gap between intentions and behavior
\citep{mathur2021meta, mathur2021effectiveness}.

Our paper addresses these concerns by meta-analyzing randomized
controlled trials (RCTs) that

\begin{itemize}
\item
  were designed to voluntarily reduce MAP consumption, rather than
  (e.g.) encouraging substitution from red to white meat or fish or
  removing meat from someone's plate
\item
  had least 25 subjects each in treatment and control, or, for
  cluster-randomized trials, at least 10 clusters in total;
\item
  measured MAP consumption, whether self-reported or observed directly,
  rather than (or in addition to) attitudes, intentions, beliefs or
  hypothetical choices;
\item
  recorded outcomes at least a single day after the start of treatment.
\end{itemize}

Additionally, studies needed to be publicly circulated by December 2023
and published in English.

We coded 33 papers
\citep{abrahamse2007, alblas2023, aldoh2023, allen2002, andersson2021, acharya2004, berndsen2005, bertolaso2015, bianchi2022, bochmann2017, bschaden2020, carfora2023, coker2022, cooney2016, fehrenbach2015, feltz2022, griesoph2021, haile2021, hatami2018, hennessy2016, jalil2023, lacroix2020, mathur2021effectiveness, mattson2020, merrill2009, norris2014, peacock2017, piester2020, polanco2022, sparkman2017, sparkman2020, sparkman2021, weingarten2022}
comprising 39 separate studies, 107 interventions, and approximately
78000 subjects. (Some treatments were administered at the level of day
or cafeteria and did not record their number of human subjects.) The
earliest paper was published in 2002 \citep{allen2002}, and a majority
(19 of 33) have been published since 2020.

We also coded a supplementary dataset of 14 papers aimed at reducing
consumption of red and/or processed meat (RPM)
\citep{carfora2017correlational, carfora2017randomised, carfora2019, carfora2019informational, delichatsios2001, dijkstra2022, emmons2005cancer, emmons2005project, jaacks2014, james2015, lee2018, perino2022, schatzkin2000, sorensen2005},
comprising 14 studies, 19 interventions, and approximately 8000
subjects. This was to provide a comparison between studies that aimed to
reduce overall MAP consumption and those that aimed to reduce RPM and
measured only changes in those categories, i.e.~not recording potential
substitution to other MAP products \citep{mathur2022ethical}.

Last, we compiled a third dataset of 780 excluded studies, along with
their reason(s) for exclusion.

\section{Results}\label{sec2}

\subsection{Three theoretical categories: persuasion, choice
architecture, and norms}\label{sec2.1}

\begin{table}[!h]
\centering
\caption{\label{tab:tab:table_one}Nudge, norms, and persuasion approaches to MAP reduction}
\centering
\begin{tabular}[t]{lrrll}
\toprule
Approach & N (Studies) & N (Interventions) & N (subjects) & Glass's $\Delta$ (SE)\\
\midrule
\textbf{Overall} & 39 & 106 & 78000 & 0.0603** (0.0213)\\
Nudge & 1 & 1 & 7900 & 0.1670 (0.2790)\\
Norms & 11 & 18 & 53100 & 0.0739 (0.0352)\\
Persuasion & 26 & 79 & 16900 & 0.0683* (0.0265)\\
Norms + Persuasion & 5 & 8 & 600 & 0.1581 (0.1905)\\
\bottomrule
\multicolumn{5}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001}\\
\end{tabular}
\end{table}

\begin{table}[!h]
\centering
\caption{\label{tab:tab:table_two}Three types of persuasion}
\centering
\begin{tabular}[t]{lrrl}
\toprule
Persuasion Approach & N (Studies) & N (Interventions) & Glass's $\Delta$ (SE)\\
\midrule
Health & 15 & 24 & 0.0938 (0.0429)\\
Environment & 12 & 20 & 0.0842 (0.0582)\\
Animal Welfare & 13 & 60 & 0.0100 (0.0130)\\
\bottomrule
\multicolumn{4}{l}{\rule{0pt}{1em}* p $<$ 0.05, ** p $<$ 0.01, *** p $<$ 0.001.}\\
\end{tabular}
\end{table}

Studies in our database pursued one or more of three main theories of
change: nudges, norms, and persuasion, or a combination of norms and
persuasion. Table 1 reports the distribution of studies, interventions,
and subjects (approximately) per approach.

\textbf{Nudge} studies manipulate features of an environment to
non-obtrusively guide people towards a desired choice
\citep{thaler2009}. Although nudges are frequently implemented in the
diet literature writ large
\citep{olafsson2024, cadario2020, szaszi2018}, only one study that
focused on MAP reduction met our inclusion criteria
\citep{andersson2021}. That study manipulated the salience of a
plant-based dish by placing it either at the top or bottom of a menu in
a university cafeteria in Sweden.

\textbf{Norm} studies manipulate perceptions of the popularity of
desired outcomes, e.g.~plant-based dishes \citep{sparkman2021} or using
re-usable mugs\citep{loschelder2019}. Norms might be descriptive (``33\%
of British people\ldots successfully engaged in one or
more\ldots behaviours to eat less meat'' \citep{aldoh2023}), injunctive
(e.g.~a message with a frowning face for subjects who eat more meat than
the average person in their country or a smiling face for those who eat
less \citep{alblas2023}), or dynamic, i.e.~they tell subjects that the
number of people engaging in a desired behavior is increasing over time
\citep{aldoh2023, coker2022, sparkman2017, sparkman2020, sparkman2021}.
With regards to MAP reduction, this is a comparatively young literature,
with the first paper appearing in 2017.

\textbf{Persuasion} studies, which formed the majority in our database,
appeal directly to people about eating less meat. Arguments are
typically centered around health \citep{lacroix2020}, the environment
\citep{carfora2023} \textemdash typically climate change \textemdash and
animal welfare \citep{haile2021}. Some are designed to be emotionally
activating, e.g.~presenting upsetting footage of factory farms
\citep{bertolaso2015}, while others present facts more dispassionately,
e.g.~about the relationship between diet and colorectal cancer
\citep{hatami2018}.

Many persuasion studies provide information in multiple categories at
once, e.g.~a video on animal welfare and health reasons to cut back
\citep{feltz2022} or a leaflet with information in all three categories
\citep{hennessy2016}. Table 2 displays the distribution of persuasion
studies within the three categories. (Note that because many studies
present more than one category of message, the number of studies and
interventions will sum to more than the total number of persuasion
studies and interventions.)

Finally, a handful of studies combines \textbf{norms and persuasion}
approaches
\citep{hennessy2016, carfora2023, lacroix2020, mattson2020, piester2020}.
These interventions typically suggest reasons to eat less meat side by
side with information about changing consumer habits in society.

\subsection{An overall small effect}\label{sec2.2}

Our overall meta-analytic effect size is \(\Delta\) = 0.0603 (SE =
0.0213), p = .0097. The aggregate effect is statistically significant,
but does not indicate a meaningful reduction.

Figure 1 displays the distribution of effect sizes, grouped by paper,
with each individual point representing an intervention. The overall
effect size is plotted at the bottom.

\begin{verbatim}
## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_point()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_errorbarh()`).
\end{verbatim}

\includegraphics{results/figures/forest_plot_nulls_and_cis_-1}

\begin{verbatim}
## # A tibble: 13 x 7
##    author     year      d  se_d neg_null_pos lower_bound upper_bound
##    <chr>     <int>  <dbl> <dbl>        <int>       <dbl>       <dbl>
##  1 Bertolaso  2015  0.293 0.137            0      0.0249     0.560  
##  2 Bianchi    2022  0.529 0.190            1      0.156      0.901  
##  3 Carfora    2023  0.819 0.231            0      0.366      1.27   
##  4 Carfora    2023  0.810 0.233            0      0.353      1.27   
##  5 Carfora    2023  0.530 0.220            0      0.0983     0.962  
##  6 Carfora    2023  0.513 0.228            1      0.0663     0.960  
##  7 Mattson    2020 -0.380 0.190            0     -0.754     -0.00712
##  8 Merrill    2009  0.707 0.196            1      0.323      1.09   
##  9 Peacock    2017 -0.538 0.213           -1     -0.955     -0.120  
## 10 Piester    2020  0.509 0.189            1      0.139      0.880  
## 11 Polanco    2022  0.356 0.174            0      0.0153     0.697  
## 12 Polanco    2022 -0.356 0.177            0     -0.702     -0.0101 
## 13 Sparkman   2017  0.319 0.141            1      0.0433     0.595
\end{verbatim}

This small effect may come as a surprise to readers of previous reviews,
which typically found more positive results
\citep{mathur2021meta, meier2022, chang2023}. We attribute this
difference to our stricter inclusion criteria. For instance, of the ten
largest effect sizes recorded in \citep{mathur2021effectiveness}, nine
were non-consumption outcomes and the tenth came from a non-randomized
design. (\citep{bianchi2018conscious} also found effects on intentions
and attitudes but no evidence of effects on behavior.)

As told by the papers in our dataset, 95 of 107 interventions had null
effects. However, many studies present a variety of wide variety of
outcomes and lead with, e.g., a gender-moderated effect
\citep{piester2020} or the relationship between an underlying attitude
measure and consumption outcomes \citep{berndsen2005}. Others presented
meat reduction as one of many components of a broader program of
behavior change \citep{abrahamse2007}.

We find some evidence of publication bias in our dataset.

\subsection{Red and Processed Meat is an easier
target}\label{red-and-processed-meat-is-an-easier-target}

On average, interventions aimed at reducing consumption of red and
processed meat are considerably more effective than MAP reduction
interventions are: \(\Delta\) = 0.2493 \text{(SE = 0.0707)}, p = .0045.
Each of these studies employs persuasion, and a majority (16/19) appeal
to personal health. Moreover, many of these interventions are aimed at
older people who have had serious health issues, e.g.~cancer survivors
\citep{lee2018, james2015}.

However, the effect of these interventions on MAP reduction
\emph{overall} is unknown because these studies do not report on
consumption of white meat and/or fish. Red meat is of special concern
for its environmental and health consequences \citep{grummon2023}, but
chicken is arguably worse for animals on a pound-for-pound basis
\citep{mathur2022}. For some plausible patterns of substitution, these
interventions are a net positive for personal health and the environment
but a net negative for animal welfare.

\subsection{Health appeals are generally moderately effective,
especially when aimed at older, sicker
people}\label{health-appeals-are-generally-moderately-effective-especially-when-aimed-at-older-sicker-people}

\subsection{Environmental appeals, especially those aimed at college
students, have moderate positive
effects}\label{environmental-appeals-especially-those-aimed-at-college-students-have-moderate-positive-effects}

\subsection{Animal welfare appeals are almost always
ineffective}\label{animal-welfare-appeals-are-almost-always-ineffective}

Di Gennaro also finds null results on animals

\subsection{Norms work sometimes, but it is not clear why or
when}\label{norms-work-sometimes-but-it-is-not-clear-why-or-when}

\subsection{Nudges seem to work but the evidence is
scant}\label{nudges-seem-to-work-but-the-evidence-is-scant}

\begin{itemize}
\tightlist
\item
  we also have reason to think that they won't scale (from other fields)
\end{itemize}

\subsection{Heterogeneity by country, self-reporting,cluster assignemnt,
delivery
method}\label{heterogeneity-by-country-self-reportingcluster-assignemnt-delivery-method}

\subsection{These studies are often underpowered to detect effects they
actually
find}\label{these-studies-are-often-underpowered-to-detect-effects-they-actually-find}

\begin{itemize}
\tightlist
\item
  X studies do power calculations, and Y of those find results smaller
  than they're looking for,
\item
  they also plan effect sizes based on recruited sample rather than
  follow-up
\item
  plan for small effects and attrition
\end{itemize}

\subsection{Open science practices are associated with marginally larger
effect
sizes}\label{open-science-practices-are-associated-with-marginally-larger-effect-sizes}

\section{Methods}\label{sec3}

\begin{itemize}
\tightlist
\item
  Search
\item
  Coding
\item
  Meta-analysis
\end{itemize}

\section{Discussion}\label{sec4}

\begin{itemize}
\tightlist
\item
  in this article, we
\item
  we are enocuraged by increasing rigor
\item
  we look forward to seeing
\end{itemize}

\backmatter

\bmhead{Supplementary information}

\bmhead{Acknowledgments}

\section*{Declarations}\label{declarations}
\addcontentsline{toc}{section}{Declarations}

\section{Appendix}\label{secA1}

A LOT will go here

\section{Bibliography}\label{bibliography}

\renewcommand\refname{References}
\bibliography{./manuscript/vegan-refs.bib}


\end{document}
