---
title: "vegan-meta-pap"
author: "Seth Green"
date: "2023-11-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

**libraries, functions, options, and data **
fake dataset for now
```{r setup, message=F}

#' libraries
library(metafor, quietly = T)
library(dplyr, warn.conflicts = F)
library(ggplot2, warn.conflicts = F)
library(knitr)
library(lubridate, warn.conflicts = F)
library(purrr)
library(sessioninfo)
library(stringr)
library(tidyr, warn.conflicts = F)
library(tibble)

#' functions
source("https://raw.githubusercontent.com/setgree/sv-meta/main/code/functions/map_robust.R")
source('https://raw.githubusercontent.com/setgree/sv-meta/main/code/functions/sum_lm.R')
options(scipen = 99)

set.seed(11111988)
#' data

dat <- data.frame(study_name = c('a study', 'b study', 'c study', 'd study', 
                                 'e study', 'f study', 'g study', 'h study', 
                                 'i study', 'j study', 'k study', 'l study',
                                 'm study', 'n study', 'o study', 'p study'),
                  u_s_t  = abs(rnorm(16, 1, 1)),
                  ctrl_sd = abs(rnorm(16,1,1)),
                  cluster_var = rbinom(16, 1, 0.4),
                  theory = sample(1:3, 16, replace = T),
                  self_report = rbinom(16, 1, 0.25),
                  leaflet = rbinom(16, 1, 0.25),
                  delay = sample(1:30, 16, replace = T),
                  unique_study_id = 1:16)

#' add d, var_d, and se_d

```

Average effect?

```{r avg_eff}
dat |> map_robust()
#' include a forest plot here
```


publication bias
```{r pub_bias}
dat |> sum_lm()

dat |> ggplot(aes(d, se_d)) + geom_point(aes(color = theory)) + 
  stat_smooth(method = 'lm', se = F, color = 'black') + theme_minimal() +
  ggtitle('relationship between effect size and standard erors')
```

differences by clustering, theory and self-report? 

```{r cluster}

dat |> split(~cluster_var) |> imap(~map_robust(.x) |> kable('markdown'))
dat |> split(~theory) |> imap(~map_robust(.x) |> kable('markdown'))
dat |> split(~self_report) |> imap(~map_robust(.x) |> kable('markdown'))
```

do leaflet studies work? 

```{r leaflet}
dat |> filter(leaflet == 1) |> map_robust()
```

Any relationship with delay and outcome?
```{r delay}
dat |> sum_lm(d, delay)
dat |> ggplot(aes(d, delay)) + geom_point() + 
  stat_smooth(method = 'lm', se = F) + theme_minimal()
```


record computational environment
```{r reproducibility}
sessioninfo::session_info()
```