---
title: "MAP-reduction-appendix"
date: "2024-08-29"
authors: 
  - firstname: Seth Ariel
    lastname: Green
    email: setgree@stanford.edu
    affiliation: 1
    corresponding: TRUE
  - firstname: Maya 
    lastname: Mathur
    affiliation: 1
  - firstname: Benny
    lastname: Smith 
    affiliation: 2
affiliations:
  - number: 1
    info:
      orgdiv: Humane and Sustainable Food Lab
      orgname: Stanford University
  - number: 2
    info:
      orgname: Allied Scholars for Animal Protection 
output: pdf_document
bibliography: "../vegan-refs.bib"
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage{comment}
  - \usepackage{anyfontsize}
  - \usepackage{threeparttable}
---

# Appendix

## Nudge lit is a mess

### When is a norm a nudge?

What exactly a nudge is, and what sorts of interventions qualify, is a subject of scholarly debate. @thaler2009 define a nudge as "any aspect of the choice architecture that alters people’s behaviour in a predictable way, without forbidding any options or significantly changing their economic incentives. To count as a mere nudge, the intervention must be easy and cheap to avoid" (p. 6). However, which incentives count as "economic" is not self-evident, and @selinger2012 note that many of the examples cited by Thaler and Sunstein actually do alter incentives.

@hausman2010 offer a revised definition of nudges as "ways of influencing choice without limiting the choice set or making alternatives appreciably more costly in terms of time, trouble, social sanctions, and so forth" (p. 126). By this definition, an injunctive norm intervention, which implies a threat of social deviance and therefore sanction, would not qualify.

The question of whether a descriptive norm intervention is a nudge is trickier. @thaler2009 would say yes; they write that if "choice architects want to change behavior, and to do so with a nudge, they might simply inform people about what other people are doing" (p. 71). However, @hausman2010 also note that nudges are designed to address "flaws in individual decision-making" (p. 126). Is a tendency to conform a flaw or "behavioral bias" @kantorowicz2021, p. 362?

@mols2015 thread this needle by defining "unthinking conformity" as one of the "human failings" which nudges are intended to address. They contrast this approach with "persuasion," which "appeals to an individual’s ability to reason, digest new information and engage in systematic information processing" (p. 4).

Our own view is that a social norm prompt might engender a rich array of possible reactions, both cognitive and affective, and we do not assume that "unthinking conformity" is the dominant or exclusive response. Therefore, we do not classify the norms interventions in our database as nudges, though we acknowledge a burgeoning "norms-nudge" literature and that terminology may change over time (see @bicchieri2023 for discussion).

We also think that a future project might investigate exactly what reactions are occurring by asking subjects, e.g., how well they recall the message, what it made them think about, etc. A high prevalence of subjects' being unable to recall the message's specifics, for instance, but nevertheless showing signs of behavioral change would be evidence in favor of the hypothesis that norms are acting through automatic rather than reflective processes.

##Theory

* behavior change is just hard https://www.nature.com/articles/s44159-024-00305-0 & most - interventions don't work https://www.bu.edu/bulawreview/files/2023/12/STEVENSON.pdf

* but nudges claim to work – so what's going on?

* well, publication bias in nudge studies https://www.pnas.org/doi/full/10.1073/pnas.2200300119 ,

* it's easier to change beliefs https://www.aeaweb.org/articles?id=10.1257/jel.20211658 (Effect Sizes on Beliefs versus Behavior),

* nudges don't scale https://onlinelibrary.wiley.com/doi/full/10.3982/ECTA18709

* "our read is quite different' https://www.pnas.org/doi/10.1073/pnas.2200732119 automatacity is not the way forward